### ISSUE TITLE
Support CentOS 8 and a supervisor alternative

### ISSUE THREAD

**Issue by navbruce** [juanluisbaptiste/docker-postfix#16] opened 2019-10-16 23:18 UTC
The build is currently failing. Apparently `supervisor` is not available:

```
$ docker build --tag docker-postfix .
Sending build context to Docker daemon  122.4kB
Step 1/13 : FROM centos:latest

[...]

Installed:
  libxkbcommon-0.8.2-1.el8.x86_64       diffutils-3.6-5.el8.x86_64
  kbd-2.0.4-8.el8.x86_64                xkeyboard-config-2.24-3.el8.noarch
  kbd-legacy-2.0.4-8.el8.noarch         kbd-misc-2.0.4-8.el8.noarch

Complete!
Last metadata expiration check: 0:00:47 ago on Wed Oct 16 23:02:49 2019.
No match for argument: supervisor
Error: Unable to find a match
The command '/bin/sh -c yum install -y epel-release && yum update -y &&     yum install -y cyrus-sasl cyrus-sasl-plain cyrus-sasl-md5 mailx     perl supervisor postfix rsyslog     && rm -rf /var/cache/yum/*     && yum clean all' returned a non-zero code: 1
```

If I find a fix I'll report back, but I thought I should note the problem first.

**Comment by juanluisbaptiste** [comment] 2019-10-17 00:21
Sure ? I just successfully built it locally with latest CentOS image.

**Comment by navbruce** [comment] 2019-10-17 00:40
Hmm, odd. I just cloned your repo and built it and had this problem, and I only tried it with a clean local copy because it failed to build (well, my somewhat modified version) in my deployment pipeline.

**Comment by juanluisbaptiste** [comment] 2019-10-17 01:09
You are right, I forgot to use --no-cache last time, I just checked and I get the build failure.

**Comment by juanluisbaptiste** [comment] 2019-10-17 01:14
The issue is with the CentOS version, now centos:latest points to CentOS 8 and epel repo for that version does not include supervisor.

**Comment by juanluisbaptiste** [comment] 2019-10-17 02:36
Fixed, new build available.

Thanks for the heads up :+1:

**Comment by blackholegalaxy** [comment] 2019-10-22 01:32
Do you plan any update to get this working on centos 8? Any supervisor alternative?

**Comment by juanluisbaptiste** [comment] 2019-10-22 02:39
> Do you plan any update to get this working on centos 8? Any supervisor alternative?

Yes, but not in the near future, too much going on currently and this issue needs its time to be researched and properly implemented.

PR's accepted though.

**Comment by juanluisbaptiste** [comment] 2020-03-23 23:45
@blackholegalaxy 

I just pushed a new version running on Alpine + supervisor with tag _alpine_. Please test it downloading `juanluisbaptiste/postfix:alpine` and let me know how it is working.

Later I also plan to migrate from supervisor to s6-init, but I prefer going step by step.

**Comment by blackholegalaxy** [comment] 2020-03-24 00:45
Oh that's pretty nice! I will test it out tomorrow and let you know

**Comment by juanluisbaptiste** [comment] 2020-03-24 01:54
Excellent, @navbruce would you like to test it out too ?

**Comment by navbruce** [comment] 2020-03-24 02:56
I'd like to, but mail is pretty far from what I'm working on right now. Looks like a good move, though.

**Comment by juanluisbaptiste** [comment] 2020-04-09 15:49
@blackholegalaxy , did you have time to test ? for me the new alpine image is working fine, but there's issue #21 where is not working for someone else. Could you do a quick test and report back ?

**Comment by blackholegalaxy** [comment] 2020-04-09 16:04
My usage of docker-postfix is to redirect to another provider not send directly. So basically docker-postfix is not authenticated and proxying toward sparkpost smtp or other stuff. In thise case it seems it works pretty fine.

**Comment by juanluisbaptiste** [comment] 2020-04-09 16:53
> My usage of docker-postfix is to redirect to another provider as it meant to be. And it works pretty fine on the alpine image :)

Excellent, many thanks for the test.

**Comment by juanluisbaptiste** [comment] 2021-02-03 17:31
Hi,

After being running the alpine image for a long time on production systems with no issues, this week I will make this image the default  one, merging the _migrate_to_alpine_ branch into master and moving the _latest_ tag to this one.

**Comment by juanluisbaptiste** [comment] 2021-02-03 23:55
Merged migrate_to_alpine branch into master, closing this issue.

**Closed by juanluisbaptiste** 2021-02-03 23:55 UTC
Labels: enhancement
